### PR TITLE
added vicon yaw and orientation modes

### PR DESCRIPTION
**Pull request by mcamurri**
revised version of [https://github.com/openhumanoids/pronto/pull/55](55)

### CODE REVIEW

**Comment by mauricefallon** [comment]
Looks good. thanks

BTW, did you test this on a robot?

**Comment by mauricefallon** [comment]
Oh, and in future you can push new commits onto a branch and they will automagically be appended to the related pull request - so you don't need to open several

**Comment by mcamurri** [comment]
I tested on LCM logs taken from HyQ. I did not test on the robot online. 
Which branch should I push to? Anyone from our fork?

**Comment by mauricefallon** [comment]
Ok, that's fine by me.

> Which branch should I push to? Anyone from our fork?

... I don't understand this. I just merged your changes.

For **future** PRs you can update them by pushing new commits to the original branch.

**Comment by mcamurri** [comment]
Got it.

**Pull request merged**
